-- Add migration script here
CREATE TABLE keys(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    PRIMARY KEY(id),
    nip05_id TEXT NOT NULL,
    pin_hash TEXT NOT NULL,
    private_key_hash TEXT NOT NULL
);

CREATE INDEX pin_hash_idx ON public.keys USING btree (pin_hash) INCLUDE (private_key_hash);