application:
  port: 9000
  host: 0.0.0.0
  base_url: "http://0.0.0.0"
database:
  host: "127.0.0.1"
  port: 15429
  username: "postgres"
  password: "password"
  database_name: "nostrvault"
  require_ssl: false